// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://fdowkbceorqxbborsjlp.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZkb3drYmNlb3JxeGJib3JzamxwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzMyNjQ5NjEsImV4cCI6MjA0ODg0MDk2MX0.o4xINfWHJPZ-5oy3418Pyd3ghVofulLw3RfLEJaw0VY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);